name: Run JMeter Tests

on: [push, pull_request]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Copy and Modify JMeter Properties
        run: |
          cp /usr/share/jmeter/bin/jmeter.properties $GITHUB_WORKSPACE/jmeter.properties
          echo "security.manager=disable" >> $GITHUB_WORKSPACE/jmeter.properties
          echo "class.whitelist=org.apache.jmeter.save.ScriptWrapper" >> $GITHUB_WORKSPACE/jmeter.properties

      - name: Run JMeter Tests with Custom Properties
        run: |
          jmeter -n -t simple.jmx -l result.jtl -p $GITHUB_WORKSPACE/jmeter.properties
