name: Run JMeter Tests

on: [push, pull_request]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter
          
      - name: Update JMeter Properties
        run: |
          echo "security.manager=disable" >> /usr/share/jmeter/bin/jmeter.properties

      - name: Run JMeter Tests
        run: |
          jmeter -n -t simple.jmx -l result.jtl
