name: Run Postman tests with Newman

on: [push, pull_request]  # Ejecuta los tests cuando haya un push o pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Elige la versión de Node.js que prefieras

      - name: Install Newman
        run: npm install -g newman  # Instala Newman globalmente

      - name: Run Postman collection
        run: newman --version  # Reemplaza con la ruta a tu colección exportada
